version: "3"

services:
  containerd:
    build:
      context: ./containerd
      args:
        VERSION: 1.2.10
        # VERSION: 1.3.2

        # DELIM: "-"
        # VERSION: 1.4.4
    image: containerd
    cap_add:
      - SYS_ADMIN
    volumes:
      - run-containerd:/run/containerd/

  client:
    build:
      context: ./client
    image: client
    command: [ "registry:5000/workspace-full:latest", "10"]
    # command: "registry:5000/alpine:latest"
    volumes:
      - run-containerd:/run/containerd/

  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./registry:/var/lib/registry

volumes:
  run-containerd:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      # o: "size=256m,uid=1000"
