version: "3"

services:
  containerd:
    build:
      context: ./containerd
      args:
        VERSION: ${CONTAINERD_VERSION}
        DELIM: ${CONTAINERD_DELIM}
    image: containerd
    cap_add:
      - SYS_ADMIN
    volumes:
      - ${CONTAINERD_RUN_VOLUME}:/run/containerd/

  client:
    build:
      context: ./client
    image: client
    command: ${CLIENT_COMMAND}
    volumes:
      - ${CONTAINERD_RUN_VOLUME}:/run/containerd/

  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./registry:/var/lib/registry

volumes:
  run-containerd:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      # o: "size=256m,uid=1000"
